### ISSUE TITLE
Put package name in the page tilte

### ISSUE THREAD

**Issue by megapctr** [pravdomil/Elm-Packages#1]
I tend to have a few tabs open with packages I'm using together. Currently all these tabs have the title _"Elm Packages Browser"_ which makes it difficult to find which package is open in which tab.

The best solution would be to figure out how to make this workflow possible with just one tab :sweat_smile: but as a temporary workaround putting the package name in the page title would be enough.

I can work on a PR if you want support with this.

**Comment by pravdomil** [comment]
f5
